name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Qodana
        uses: JetBrains/qodana-action@v2022.3.4
        with:
          args:
            -l, jetbrains/qodana-js:2023.1-eap, --profile-name, "Project Default"


